name: cache build files

on:
  push:
    branches:
      - master
  repository_dispatch:
    event_type:
      - "sanity-deploy"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        with:
          path: site/public
          key: cache-public-${{ hashFiles('site/public/**') }}
          restore-keys: |
            cache-public-

      - uses: actions/cache@v2
        with:
          path: site/.cache
          key: cache-cache-${{ hashFiles('site/.cache/**') }}
          restore-keys: |
            cache-cache-

      - name: Install packages
        run: yarn --prefer-offline

      - name: Run site build
        env:
          GATSBY_SANITY_DATASET: ${{ secrets.GATSBY_SANITY_DATASET }}
          GATSBY_SANITY_ID: ${{ secrets.GATSBY_SANITY_ID }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: yarn workspace site build

      - name: deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --dir=site/public --prod
